# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7412adc0c187179074a30a9a0569432944ba58a41644bd207981aa26d5fe3c0a2b3db9fb9bf661f84d49671e232cb3591e0618db03c4c2656c527ef845fcc6

test:
  secret_key_base: 358e6ce5d9b017aa234f45802c54493bc684c84d5510cc2ab7bd9c426c50552a55268edd91d819f8a422de34dd35a7625a16c8849581c52bf4b258be09d68e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
